version: "3"

services:
  api:
    build: .
    image: carsdb-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: